changelog:
  categories:
    # Major level
    - title: Breaking Changes ğŸš¨
      labels:
        - "[actions] changelog: breaking"

    # Minor level
    - title: New Features ğŸ‰
      labels:
        - "[actions] changelog: feature"

    - title: Updated âœ¨
      labels:
        - "[actions] changelog: update"

    - title: Enhancements âš¡ï¸
      labels:
        - "[actions] changelog: enhancement"

    # Patch level
    - title: Bug Fixes ğŸ›
      labels:
        - "[actions] changelog: fix"

    - title: Tweaked ğŸ”§
      labels:
        - "[actions] changelog: tweak"

    - title: Documentation ğŸ“š
      labels:
        - "[actions] changelog: docs"
