changelog:
  exclude:
    authors:
      - dependabot
      - github-actions
    labels:
      - "changelog: none"

  categories:
    # Major level
    - title: Breaking Changes ğŸš¨
      labels:
        - "[actions] changelog: breaking"

    # Minor level
    - title: New Features ğŸ‰
      labels:
        - "[actions] changelog: add"

    - title: Updated âœ¨
      labels:
        - "[actions] changelog: update"

    # Patch level
    - title: Bug Fixes ğŸ›
      labels:
        - "[actions] changelog: fix"

    - title: Tweaked ğŸ”§
      labels:
        - "[actions] changelog: tweak"

    - title: Documentation ğŸ“š
      labels:
        - "[actions] changelog: docs"
